# Copyright 2025-2026 Lawrence Livermore National Security, LLC and other Pyctos Developers.
# See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: BSD-3-Clause

"""
This script is used to collect numpy ufunc names for typing.
"""

from collections.abc import Iterable
from pathlib import Path
import numpy as np

# Location of the output file
OUTPUT = Path('src/symbex/libraries/impls/numpy/ufuncs/names.py')

# Map of names to ufunc objects (excluding gufuncs)
UFUNCS = {
  name: fun
  for name, fun in vars(np).items()
  if isinstance(fun, np.ufunc) and fun.signature is None
}


def format_name_literal(alias: str, names: Iterable[str]) -> str:
  """
  Formats a type alias for literal ufunc names of some arity.
  """
  return '\n'.join([f'{alias}: TypeAlias = Literal[',
                    *[f"  '{name}'," for name in names],
                    ']'])


def format_module() -> str:
  """
  Formats the entire module file to dump.
  """
  names = UFUNCS.keys()

  preamble = '''"""
Collected numpy ufunc names for typing (excluding gufuncs).

Generated by `scripts/numpy/collect_ufuncs.py`.
"""

from typing import Literal, TypeAlias


__all__ = ['UFuncName']
'''

  return '\n'.join([
    preamble,
    '',
    '# Describes the name of a real numpy ufunc',
    format_name_literal('UFuncName', names),
    '',
  ])


if __name__ == '__main__':
  OUTPUT.parent.mkdir(parents=True, exist_ok=True)
  OUTPUT.write_text(format_module(), encoding='utf-8')
